// Navigation structure for the BirdBox app shell.
// Each top-level group appears as a tile on the home grid; tapping a group
// opens a landing page with a top tab bar for that group's screens.
const NAV = [
  {
    id: 'mybirds',
    label: 'My Birds',
    icon: 'icons/transparent/Birds.png',
    color: '#2f6f4f',
    tint: '#e3f0e9',
    blurb: 'Pedigree, genetics, and registry — the heart of BirdBox.',
    screens: [
      { id: 'birds', label: 'Birds', icon: 'icons/transparent/Birds.png',
        blurb: 'Your full flock: profiles, photos, and details for every bird you own.' },
      { id: 'genealogy', label: 'Genealogy', icon: 'icons/transparent/Genealogy.png',
        blurb: 'Visual family trees showing parents, siblings, and offspring.' },
      { id: 'genetics', label: 'Genetics', icon: 'icons/transparent/Genetics.png',
        blurb: 'Mutation calculator and pairing predictor for expected offspring traits.' },
      { id: 'registry', label: 'Registry', icon: 'icons/transparent/Registry.png',
        blurb: 'Public pedigree registry and ownership certificates.' },
      { id: 'health', label: 'Health', icon: 'icons/transparent/Health.png',
        blurb: 'Vet visits, medications, and health notes per bird.' },
      { id: 'production', label: 'Production', icon: 'icons/transparent/Production.png',
        blurb: 'Egg-laying, clutches, and hatch records.' },
      { id: 'labels', label: 'Labels', icon: 'icons/transparent/Labels.png',
        blurb: 'Print band/ID labels for cages and carriers.' },
    ],
  },
  {
    id: 'aviary',
    label: 'Aviary',
    icon: 'icons/transparent/Caging.png',
    color: '#3d6b8a',
    tint: '#e4edf3',
    blurb: 'Day-to-day husbandry: cages, feeding, and chores.',
    screens: [
      { id: 'caging', label: 'Caging', icon: 'icons/transparent/Caging.png',
        blurb: 'Cages, flights, and location assignments.' },
      { id: 'feedwater', label: 'Feed/Water', icon: 'icons/transparent/FeedWater.png',
        blurb: 'Feeding schedules and diet tracking.' },
      { id: 'supplies', label: 'Supplies', icon: 'icons/transparent/Supplies.png',
        blurb: 'Inventory of feed, medication, and supplies on hand.' },
      { id: 'cleaning', label: 'Cleaning', icon: 'icons/transparent/Cleaning.png',
        blurb: 'Cleaning schedules and checklists.' },
      { id: 'tasks', label: 'Tasks', icon: 'icons/transparent/Tasks.png',
        blurb: 'Chores and recurring to-dos.' },
      { id: 'calendar', label: 'Calendar', icon: 'icons/transparent/Calendar.png',
        blurb: 'Upcoming hatch dates, tasks, and reminders.' },
    ],
  },
  {
    id: 'business',
    label: 'Business',
    icon: 'icons/transparent/Accounting.png',
    color: '#8a5a2f',
    tint: '#f3e9e0',
    blurb: 'Sales, invoicing, and the marketplace.',
    screens: [
      { id: 'accounting', label: 'Accounting', icon: 'icons/transparent/Accounting.png',
        blurb: 'Invoices, billing, and accounts receivable.' },
      { id: 'shipping', label: 'Shipping', icon: 'icons/transparent/Shipping.png',
        blurb: 'Book and track live-animal shipments.' },
      { id: 'classifieds', label: 'Classifieds', icon: 'icons/transparent/Classifieds.png',
        blurb: "List birds for sale or browse other breeders' listings." },
      { id: 'reports', label: 'Reports', icon: 'icons/transparent/Reports.png',
        blurb: 'Visual reports: sales, production, and inbreeding coefficients.' },
      { id: 'contacts', label: 'Contacts', icon: 'icons/transparent/Contacts.png',
        blurb: 'Buyers, sellers, and vendor address book.' },
    ],
  },
  {
    id: 'community',
    label: 'Community',
    icon: 'icons/transparent/Notifications.png',
    color: '#7a4f8a',
    tint: '#f0e6f3',
    blurb: 'Messages and alerts between breeders.',
    screens: [
      { id: 'messages', label: 'Messages', icon: 'icons/transparent/Contacts.png',
        blurb: 'Private messaging between breeders and buyers.' },
      { id: 'notifications', label: 'Notifications', icon: 'icons/transparent/Notifications.png',
        blurb: 'Alerts for sales, messages, and account activity.' },
    ],
  },
  {
    id: 'account',
    label: 'Account',
    icon: 'icons/transparent/My_Profile.png',
    color: '#555555',
    tint: '#ececec',
    blurb: 'Your profile, team, and app settings.',
    screens: [
      { id: 'myprofile', label: 'My Profile', icon: 'icons/transparent/My_Profile.png',
        blurb: 'Your personal info and account details.' },
      { id: 'myteam', label: 'My Team', icon: 'icons/transparent/My_Team.png',
        blurb: 'Manage collaborators who can access your records.' },
      { id: 'settings', label: 'Settings', icon: 'icons/transparent/Settings.png',
        blurb: 'App preferences and configuration.' },
      { id: 'privacy', label: 'Privacy', icon: 'icons/transparent/Privacy.png',
        blurb: "Control what's public, member-only, or private." },
      { id: 'cloudsync', label: 'Cloud Sync', icon: 'icons/transparent/Cloud_Sync.png',
        blurb: 'Back up and sync your data across devices.' },
      { id: 'ondevice', label: 'On Device', icon: 'icons/transparent/On_Device.png',
        blurb: 'Keep data stored locally on this device only.' },
      { id: 'help', label: 'Help', icon: 'icons/transparent/Help.png',
        blurb: 'Guides, FAQs, and support.' },
    ],
  },
];
