// Navigation structure for the BirdBox app shell.
// Home-grid groups appear as tiles on the home screen; each opens a landing
// page with a top tab bar for its screens. The "account" group is reachable
// only through the avatar button in the header, never as a home tile
// (set homeTile: false) — it folds in profile, messages, notifications,
// and settings so they don't need their own section.
const NAV = [
  {
    id: 'mybirds',
    label: 'My Birds',
    icon: 'icons/tinted/mybirds/Birds.png',
    color: '#C1694F',
    tint: '#F5E4DC',
    homeTile: true,
    blurb: 'Pedigree and genetics — the heart of BirdBox.',
    screens: [
      { id: 'birds', label: 'Birds', icon: 'icons/tinted/mybirds/Birds.png',
        blurb: 'Your full flock: profiles, photos, and details for every bird you own.' },
      { id: 'genealogy', label: 'Genealogy', icon: 'icons/tinted/mybirds/Genealogy.png',
        blurb: 'Visual family trees showing parents, siblings, and offspring.' },
      { id: 'genetics', label: 'Genetics', icon: 'icons/tinted/mybirds/Genetics.png',
        blurb: 'Mutation calculator and pairing predictor for expected offspring traits.' },
      { id: 'health', label: 'Health', icon: 'icons/tinted/mybirds/Health.png',
        blurb: 'Vet visits, medications, and health notes per bird.' },
      { id: 'production', label: 'Production', icon: 'icons/tinted/mybirds/Production.png',
        blurb: 'Egg-laying, clutches, and hatch records.' },
      { id: 'labels', label: 'Labels', icon: 'icons/tinted/mybirds/Labels.png',
        blurb: 'Print band/ID labels for cages and carriers.' },
    ],
  },
  {
    id: 'registry',
    label: 'Registry',
    icon: 'icons/tinted/registry/Registry.png',
    color: '#C79A3D',
    tint: '#F6ECD6',
    homeTile: true,
    blurb: 'The public band-number registry — search, register, or report a lost bird.',
    screens: [
      { id: 'search', label: 'Search', icon: 'icons/tinted/registry/Registry.png',
        blurb: 'Look up a band number to see its public pedigree record.' },
      { id: 'register', label: 'Register', icon: 'icons/tinted/registry/Labels.png',
        blurb: 'Register a new band number and start its official record.' },
      { id: 'lostfound', label: 'Lost & Found', icon: 'icons/tinted/registry/Notifications.png',
        blurb: 'Post or search Lost & Found alerts for missing birds.' },
    ],
  },
  {
    id: 'aviary',
    label: 'Aviary',
    icon: 'icons/tinted/aviary/Caging.png',
    color: '#7C9473',
    tint: '#E7EDE2',
    homeTile: true,
    blurb: 'Day-to-day husbandry: cages, feeding, and chores.',
    screens: [
      { id: 'caging', label: 'Caging', icon: 'icons/tinted/aviary/Caging.png',
        blurb: 'Cages, flights, and location assignments.' },
      { id: 'feedwater', label: 'Feed/Water', icon: 'icons/tinted/aviary/FeedWater.png',
        blurb: 'Feeding schedules and diet tracking.' },
      { id: 'supplies', label: 'Supplies', icon: 'icons/tinted/aviary/Supplies.png',
        blurb: 'Inventory of feed, medication, and supplies on hand.' },
      { id: 'cleaning', label: 'Cleaning', icon: 'icons/tinted/aviary/Cleaning.png',
        blurb: 'Cleaning schedules and checklists.' },
      { id: 'tasks', label: 'Tasks', icon: 'icons/tinted/aviary/Tasks.png',
        blurb: 'Chores and recurring to-dos.' },
      { id: 'calendar', label: 'Calendar', icon: 'icons/tinted/aviary/Calendar.png',
        blurb: 'Upcoming hatch dates, tasks, and reminders.' },
    ],
  },
  {
    id: 'business',
    label: 'Business',
    icon: 'icons/tinted/business/Accounting.png',
    color: '#8B5E3C',
    tint: '#EFE3D6',
    homeTile: true,
    blurb: 'Invoicing, shipping, and reports.',
    screens: [
      { id: 'accounting', label: 'Accounting', icon: 'icons/tinted/business/Accounting.png',
        blurb: 'Invoices, billing, and accounts receivable.' },
      { id: 'shipping', label: 'Shipping', icon: 'icons/tinted/business/Shipping.png',
        blurb: 'Book and track live-animal shipments.' },
      { id: 'reports', label: 'Reports', icon: 'icons/tinted/business/Reports.png',
        blurb: 'Visual reports: sales, production, and inbreeding coefficients.' },
      { id: 'contacts', label: 'Contacts', icon: 'icons/tinted/business/Contacts.png',
        blurb: 'Buyers, sellers, and vendor address book.' },
    ],
  },
  {
    id: 'classifieds',
    label: 'Classifieds',
    icon: 'icons/tinted/classifieds/Classifieds.png',
    color: '#C9776B',
    tint: '#F5E1DD',
    homeTile: true,
    blurb: 'Buy, sell, and browse listings from other breeders.',
    screens: [
      { id: 'browse', label: 'Browse', icon: 'icons/tinted/classifieds/Classifieds.png',
        blurb: 'Browse birds for sale from other breeders.' },
      { id: 'mylistings', label: 'My Listings', icon: 'icons/tinted/classifieds/Notes.png',
        blurb: "Manage the listings you've posted." },
    ],
  },
  {
    id: 'account',
    label: 'Account',
    icon: 'icons/tinted/account/My_Profile.png',
    color: '#8A7B6C',
    tint: '#EDE8E2',
    homeTile: false,
    blurb: 'Your profile, messages, and app settings.',
    screens: [
      { id: 'myprofile', label: 'My Profile', icon: 'icons/tinted/account/My_Profile.png',
        blurb: 'Your personal info and account details.' },
      { id: 'messages', label: 'Messages', icon: 'icons/tinted/account/Contacts.png',
        blurb: 'Private messages between breeders and buyers.' },
      { id: 'notifications', label: 'Notifications', icon: 'icons/tinted/account/Notifications.png',
        blurb: 'Alerts for sales, messages, and account activity.' },
      { id: 'myteam', label: 'My Team', icon: 'icons/tinted/account/My_Team.png',
        blurb: 'Manage collaborators who can access your records.' },
      { id: 'settings', label: 'Settings', icon: 'icons/tinted/account/Settings.png',
        blurb: 'App preferences and configuration.' },
      { id: 'privacy', label: 'Privacy', icon: 'icons/tinted/account/Privacy.png',
        blurb: "Control what's public, member-only, or private." },
      { id: 'cloudsync', label: 'Cloud Sync', icon: 'icons/tinted/account/Cloud_Sync.png',
        blurb: 'Back up and sync your data across devices.' },
      { id: 'ondevice', label: 'On Device', icon: 'icons/tinted/account/On_Device.png',
        blurb: 'Keep data stored locally on this device only.' },
      { id: 'help', label: 'Help', icon: 'icons/tinted/account/Help.png',
        blurb: 'Guides, FAQs, and support.' },
    ],
  },
];
